repository:


  name: jaajko.github.io

  description: source code for jaajko.github.io

  homepage: https://jaajko.github.io/

  private: false


  has_issues: true 

  has_projects: false

  has_wiki: false

  has_downloads: false


  # default_branch: main


  allow_squash_merge: true

  allow_merge_commit: true

  allow_rebase_merge: true


labels:
  - name: bug
    color: CC0000
  - name: no-stale
    color: DAF7A6
